---

# Parameter file for running hodpy and HOD_Mock_Pipeline
# Contains the paths to the relevant folders and such for SOAP, snapshots, etc.
# Also includes N and L for convenience

Paths:
  soap_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/HYDRO_FIDUCIAL/SOAP-HBT/halo_properties_0073.hdf5 # SOAP output file at a certain redshift
  soap_meta_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/HYDRO_FIDUCIAL/SOAP-HBT/ # folder containing folders for different redshifts
  snapshot_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/HYDRO_FIDUCIAL/snapshots/flamingo_0073/flamingo_0073.hdf5
  lightcone_path: /cosma8/data/dp004/dc-elbe1/FLAMINGO/halo_lightcones/L1000N1800/HYDRO_FIDUCIAL/halo_lightcone.hdf5
  params_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/HYDRO_FIDUCIAL/used_parameters.yml
  output_list_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/HYDRO_FIDUCIAL/output_list.txt # has the redshift of each snapshot

Params:
  #these might need to be changed
  N: 1800
  L: 1000
  redshift: 0.2
  photsys: "S"
  #num_redshifts: 1 # Number of redshifts for which the mass function is measured
  max_redshift: 7.0 # Highest redshift for which the mass function is measured (if it's measured before halos exist, things break)
  mag_faint: 20.0
  mag_faint_type: "apparent" # Whether the faint magnitude limit is apparent or absolute; depends on whether mock is cut-sky or cubic-box
  #these probably don't need to be changed in most situations
  log_mass_min: -11
  logMmin: 10.3 # Minimum mass of unresolved halo tracers for BGS or what have you
  logMmax: 11 # Maximum mass of unresolved halo tracers; SHOULD BE CHANGED FOR FLAMINGO
  ntracer: 3 # Number of satellite tracers for each halo
  particles: False # use particles to position galaxy tracers if True, NFW if False; True not yet supported with Flamingo
  mag_faint_extrapolate: -17 #If specified, the HOD parameters Mmin and M1 will be extrapolated linearly fainter than this magnitude. Default is -17

Misc:
  random_seed: 1
  halo_type: peregrinus # soap, peregrinus, ...

Labels:
  sim_label: "L1000N1800_HYDRO" # just for labelling output files